name: GA Test

on:
  pull_request:
    types:
      - closed
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - master
  release:
    types:
      - prereleased
      - released

defaults:
  run:
    shell: bash

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    uses: gokaygurcan/ga-collection/.github/workflows/setup.yml@main
    secrets: inherit
