name: GA Test

on:
  pull_request:
    types:
      - closed
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - master
  release:
    types:
      - prereleased
      - released

defaults:
  run:
    shell: bash

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - id: triage
      name: Triage
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true

    - id: checkout
      name: Checkout
      uses: actions/checkout@v2

    - id: setup-node
      name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - id: cache-dependencies
      name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          **/node_modules
          **/.cache
        key: node-modules-${{ hashFiles('package.json') }}

    - id: install-dependencies
      name: Install dependencies
      if: |
        (steps.cache-dependencies.outputs.cache-hit != 'true')
      run: |
        npm install

    - id: sanity-check
      name: Sanity check
      uses: gokaygurcan/ga-collection/.github/workflows/setup/sanity-check.yml@main
      secrets: inherit
